### PR TITLE
replys 分出來 + 對白微調

### PR DESCRIPTION
**Pull request by aptxyz**

### CODE REVIEW

**Comment by rechtar** [comment]
just found that this was reopened! still ready for merge now? @aptxyz

**Comment by aptxyz** [comment]
@rechtar urrrr... sure y not, b38. though i nvr really understand how does the pull push syst wrk.

**Comment by rechtar** [comment]
@aptxyz O_O you mean you never use Git (or Mercurial or whatever) outside of this?

**Comment by aptxyz** [comment]
てへぺろ☆(・ω<)。

**Pull request merged**
